name: dependency_scanner
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/g0rdan/flutter_dependency_scanner

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.16.0
